// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_failure = "CgkIp4bqwJwIEAIQBA"; // <GPGSID>
        public const string achievement_the_rebel_path = "CgkIp4bqwJwIEAIQCA"; // <GPGSID>
        public const string achievement_the_frequent_traveler = "CgkIp4bqwJwIEAIQCw"; // <GPGSID>
        public const string achievement_triumph = "CgkIp4bqwJwIEAIQAw"; // <GPGSID>
        public const string achievement_youve_been_trapped = "CgkIp4bqwJwIEAIQCQ"; // <GPGSID>
        public const string achievement_redemption = "CgkIp4bqwJwIEAIQAg"; // <GPGSID>
        public const string achievement_it_goes_down = "CgkIp4bqwJwIEAIQBg"; // <GPGSID>
        public const string achievement_the_hero = "CgkIp4bqwJwIEAIQDg"; // <GPGSID>
        public const string achievement_first_step = "CgkIp4bqwJwIEAIQAQ"; // <GPGSID>
        public const string achievement_the_level_master = "CgkIp4bqwJwIEAIQDQ"; // <GPGSID>
        public const string achievement_the_conqueror = "CgkIp4bqwJwIEAIQDw"; // <GPGSID>
        public const string achievement_speeed = "CgkIp4bqwJwIEAIQBw"; // <GPGSID>
        public const string achievement_on_the_edge = "CgkIp4bqwJwIEAIQBQ"; // <GPGSID>
        public const string achievement_the_initiate = "CgkIp4bqwJwIEAIQCg"; // <GPGSID>
        public const string achievement_the_distinguished_explorer = "CgkIp4bqwJwIEAIQDA"; // <GPGSID>

}

